[package]
name = "concurrency"
version = "0.1.0"
authors = ["oysx <ryukonoya@gmail.com>"]
edition = "2024"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
